priority:
  file:
    path: './PRIORIDADES.xlsx'
    sheet: 'Hoja1'

  columns:
    client_id: 'client_id'
    importance: 'importance'

requests:
  file:
    path: './STOCK.xlsx'
    sheet: 'Ventas'

  columns:
    this_month: 'JAN 2024'
    client_description: 'Descripci칩n de cliente 2'
    client_id: 'ID de cliente CMPC'
    client_group_description: 'Descripci칩n del grupo de cliente'
    location: 'Ubicaci칩n'
    product_id: 'ID de producto'

batches:
  file:
    path: './STOCK.xlsx'
    sheet: 'Format'
    extra_rows: 1

  columns:
    guide_column: 'Lote'
    batch_id: 'Lote'
    ship_date: 'Fecha Nave'
    mill: 'Planta'
    center_name: 'Nombre Centro'
    product_id: 'Material'
    arrived_mass: 'Net Arrib (LU)'
    mass_in_transit: 'Net en Tr치ns'